var AssignArrayDynamicL2L = artifacts.require('./AssignArrayDynamicL2L.sol');
var AssignArrayDynamicL2M = artifacts.require('./AssignArrayDynamicL2M.sol');
var AssignArrayDynamicL2S = artifacts.require('./AssignArrayDynamicL2S.sol');
var AssignArrayDynamicM2L = artifacts.require('./AssignArrayDynamicM2L.sol');
var AssignArrayDynamicM2M = artifacts.require('./AssignArrayDynamicM2M.sol');
var AssignArrayDynamicM2S = artifacts.require('./AssignArrayDynamicM2S.sol');
var AssignArrayDynamicMultiL2L = artifacts.require('./AssignArrayDynamicMultiL2L.sol');
var AssignArrayDynamicMultiL2M = artifacts.require('./AssignArrayDynamicMultiL2M.sol');
var AssignArrayDynamicMultiL2S = artifacts.require('./AssignArrayDynamicMultiL2S.sol');
var AssignArrayDynamicMultiM2L = artifacts.require('./AssignArrayDynamicMultiM2L.sol');
var AssignArrayDynamicMultiM2M = artifacts.require('./AssignArrayDynamicMultiM2M.sol');
var AssignArrayDynamicMultiM2S = artifacts.require('./AssignArrayDynamicMultiM2S.sol');
var AssignArrayDynamicMultiS2L = artifacts.require('./AssignArrayDynamicMultiS2L.sol');
var AssignArrayDynamicMultiS2M = artifacts.require('./AssignArrayDynamicMultiS2M.sol');
var AssignArrayDynamicMultiS2S = artifacts.require('./AssignArrayDynamicMultiS2S.sol');
var AssignArrayDynamicS2L = artifacts.require('./AssignArrayDynamicS2L.sol');
var AssignArrayDynamicS2M = artifacts.require('./AssignArrayDynamicS2M.sol');
var AssignArrayDynamicS2S = artifacts.require('./AssignArrayDynamicS2S.sol');
var AssignArrayDynamicStructL2L = artifacts.require('./AssignArrayDynamicStructL2L.sol');
var AssignArrayDynamicStructL2M = artifacts.require('./AssignArrayDynamicStructL2M.sol');
var AssignArrayDynamicStructL2S = artifacts.require('./AssignArrayDynamicStructL2S.sol');
var AssignArrayDynamicStructM2M = artifacts.require('./AssignArrayDynamicStructM2M.sol');
var AssignArrayDynamicStructS2L = artifacts.require('./AssignArrayDynamicStructS2L.sol');
var AssignArrayDynamicStructS2M = artifacts.require('./AssignArrayDynamicStructS2M.sol');
var AssignArrayDynamicStructS2S = artifacts.require('./AssignArrayDynamicStructS2S.sol');
var AssignArrayFixedSizeL2L = artifacts.require('./AssignArrayFixedSizeL2L.sol');
var AssignArrayFixedSizeL2M = artifacts.require('./AssignArrayFixedSizeL2M.sol');
var AssignArrayFixedSizeL2S = artifacts.require('./AssignArrayFixedSizeL2S.sol');
var AssignArrayFixedSizeM2L = artifacts.require('./AssignArrayFixedSizeM2L.sol');
var AssignArrayFixedSizeM2M = artifacts.require('./AssignArrayFixedSizeM2M.sol');
var AssignArrayFixedSizeM2S = artifacts.require('./AssignArrayFixedSizeM2S.sol');
var AssignArrayFixedSizeMappingL2L = artifacts.require('./AssignArrayFixedSizeMappingL2L.sol');
var AssignArrayFixedSizeMappingL2S = artifacts.require('./AssignArrayFixedSizeMappingL2S.sol');
var AssignArrayFixedSizeMappingS2L = artifacts.require('./AssignArrayFixedSizeMappingS2L.sol');
var AssignArrayFixedSizeMappingS2S = artifacts.require('./AssignArrayFixedSizeMappingS2S.sol');
var AssignArrayFixedSizeMultiL2L = artifacts.require('./AssignArrayFixedSizeMultiL2L.sol');
var AssignArrayFixedSizeMultiL2M = artifacts.require('./AssignArrayFixedSizeMultiL2M.sol');
var AssignArrayFixedSizeMultiL2S = artifacts.require('./AssignArrayFixedSizeMultiL2S.sol');
var AssignArrayFixedSizeMultiM2L = artifacts.require('./AssignArrayFixedSizeMultiM2L.sol');
var AssignArrayFixedSizeMultiM2M = artifacts.require('./AssignArrayFixedSizeMultiM2M.sol');
var AssignArrayFixedSizeMultiM2S = artifacts.require('./AssignArrayFixedSizeMultiM2S.sol');
var AssignArrayFixedSizeMultiS2L = artifacts.require('./AssignArrayFixedSizeMultiS2L.sol');
var AssignArrayFixedSizeMultiS2M = artifacts.require('./AssignArrayFixedSizeMultiS2M.sol');
var AssignArrayFixedSizeMultiS2S = artifacts.require('./AssignArrayFixedSizeMultiS2S.sol');
var AssignArrayFixedSizeS2L = artifacts.require('./AssignArrayFixedSizeS2L.sol');
var AssignArrayFixedSizeS2M = artifacts.require('./AssignArrayFixedSizeS2M.sol');
var AssignArrayFixedSizeS2S = artifacts.require('./AssignArrayFixedSizeS2S.sol');
var AssignArrayFixedSizeStructL2L = artifacts.require('./AssignArrayFixedSizeStructL2L.sol');
var AssignArrayFixedSizeStructL2M = artifacts.require('./AssignArrayFixedSizeStructL2M.sol');
var AssignArrayFixedSizeStructL2S = artifacts.require('./AssignArrayFixedSizeStructL2S.sol');
var AssignArrayFixedSizeStructM2M = artifacts.require('./AssignArrayFixedSizeStructM2M.sol');
var AssignArrayFixedSizeStructS2L = artifacts.require('./AssignArrayFixedSizeStructS2L.sol');
var AssignArrayFixedSizeStructS2M = artifacts.require('./AssignArrayFixedSizeStructS2M.sol');
var AssignArrayFixedSizeStructS2S = artifacts.require('./AssignArrayFixedSizeStructS2S.sol');
var AssignMappingArrayL2L = artifacts.require('./AssignMappingArrayL2L.sol');
var AssignMappingArrayS2L = artifacts.require('./AssignMappingArrayS2L.sol');
var AssignMappingL2L = artifacts.require('./AssignMappingL2L.sol');
var AssignMappingNestedL2L = artifacts.require('./AssignMappingNestedL2L.sol');
var AssignMappingNestedS2L = artifacts.require('./AssignMappingNestedS2L.sol');
var AssignMappingS2L = artifacts.require('./AssignMappingS2L.sol');
var AssignMappingStructL2L = artifacts.require('./AssignMappingStructL2L.sol');
var AssignMappingStructS2L = artifacts.require('./AssignMappingStructS2L.sol');
var AssignStructArrayDynamicL2L = artifacts.require('./AssignStructArrayDynamicL2L.sol');
var AssignStructArrayDynamicL2S = artifacts.require('./AssignStructArrayDynamicL2S.sol');
var AssignStructArrayDynamicMultiL2L = artifacts.require('./AssignStructArrayDynamicMultiL2L.sol');
var AssignStructArrayDynamicMultiL2S = artifacts.require('./AssignStructArrayDynamicMultiL2S.sol');
var AssignStructArrayDynamicMultiS2L = artifacts.require('./AssignStructArrayDynamicMultiS2L.sol');
var AssignStructArrayDynamicMultiS2S = artifacts.require('./AssignStructArrayDynamicMultiS2S.sol');
var AssignStructArrayDynamicS2L = artifacts.require('./AssignStructArrayDynamicS2L.sol');
var AssignStructArrayDynamicS2S = artifacts.require('./AssignStructArrayDynamicS2S.sol');
var AssignStructArrayFixedSizeL2L = artifacts.require('./AssignStructArrayFixedSizeL2L.sol');
var AssignStructArrayFixedSizeL2M = artifacts.require('./AssignStructArrayFixedSizeL2M.sol');
var AssignStructArrayFixedSizeL2S = artifacts.require('./AssignStructArrayFixedSizeL2S.sol');
var AssignStructArrayFixedSizeM2L = artifacts.require('./AssignStructArrayFixedSizeM2L.sol');
var AssignStructArrayFixedSizeM2M = artifacts.require('./AssignStructArrayFixedSizeM2M.sol');
var AssignStructArrayFixedSizeM2S = artifacts.require('./AssignStructArrayFixedSizeM2S.sol');
var AssignStructArrayFixedSizeMultiL2L = artifacts.require('./AssignStructArrayFixedSizeMultiL2L.sol');
var AssignStructArrayFixedSizeMultiL2M = artifacts.require('./AssignStructArrayFixedSizeMultiL2M.sol');
var AssignStructArrayFixedSizeMultiL2S = artifacts.require('./AssignStructArrayFixedSizeMultiL2S.sol');
var AssignStructArrayFixedSizeMultiM2L = artifacts.require('./AssignStructArrayFixedSizeMultiM2L.sol');
var AssignStructArrayFixedSizeMultiM2M = artifacts.require('./AssignStructArrayFixedSizeMultiM2M.sol');
var AssignStructArrayFixedSizeMultiM2S = artifacts.require('./AssignStructArrayFixedSizeMultiM2S.sol');
var AssignStructArrayFixedSizeMultiS2L = artifacts.require('./AssignStructArrayFixedSizeMultiS2L.sol');
var AssignStructArrayFixedSizeMultiS2M = artifacts.require('./AssignStructArrayFixedSizeMultiS2M.sol');
var AssignStructArrayFixedSizeMultiS2S = artifacts.require('./AssignStructArrayFixedSizeMultiS2S.sol');
var AssignStructArrayFixedSizeS2L = artifacts.require('./AssignStructArrayFixedSizeS2L.sol');
var AssignStructArrayFixedSizeS2M = artifacts.require('./AssignStructArrayFixedSizeS2M.sol');
var AssignStructArrayFixedSizeS2S = artifacts.require('./AssignStructArrayFixedSizeS2S.sol');
var AssignStructMappingL2L = artifacts.require('./AssignStructMappingL2L.sol');
var AssignStructMappingL2S = artifacts.require('./AssignStructMappingL2S.sol');
var AssignStructMappingS2L = artifacts.require('./AssignStructMappingS2L.sol');
var AssignStructMappingS2S = artifacts.require('./AssignStructMappingS2S.sol');
var DeleteMemoryArrayDynamic = artifacts.require('./DeleteMemoryArrayDynamic.sol');
var DeleteMemoryArrayDynamicMulti = artifacts.require('./DeleteMemoryArrayDynamicMulti.sol');
var DeleteMemoryArrayDynamicStruct = artifacts.require('./DeleteMemoryArrayDynamicStruct.sol');
var DeleteMemoryArrayFixedSize = artifacts.require('./DeleteMemoryArrayFixedSize.sol');
var DeleteMemoryArrayFixedSizeMulti = artifacts.require('./DeleteMemoryArrayFixedSizeMulti.sol');
var DeleteMemoryArrayFixedSizeStruct = artifacts.require('./DeleteMemoryArrayFixedSizeStruct.sol');
var DeleteStorageArrayDynamic = artifacts.require('./DeleteStorageArrayDynamic.sol');
var DeleteStorageArrayDynamicMulti = artifacts.require('./DeleteStorageArrayDynamicMulti.sol');
var DeleteStorageArrayDynamicStruct = artifacts.require('./DeleteStorageArrayDynamicStruct.sol');
var DeleteStorageArrayFixedMapping = artifacts.require('./DeleteStorageArrayFixedMapping.sol');
var DeleteStorageArrayFixedSize = artifacts.require('./DeleteStorageArrayFixedSize.sol');
var DeleteStorageArrayFixedSizeMulti = artifacts.require('./DeleteStorageArrayFixedSizeMulti.sol');
var DeleteStorageArrayFixedSizeStruct = artifacts.require('./DeleteStorageArrayFixedSizeStruct.sol');
var DeleteValueTypes = artifacts.require('./DeleteValueTypes.sol');
var InitMemoryArrayDynamic = artifacts.require('./InitMemoryArrayDynamic.sol');
var InitMemoryArrayDynamicMulti = artifacts.require('./InitMemoryArrayDynamicMulti.sol');
var InitMemoryArrayDynamicStruct = artifacts.require('./InitMemoryArrayDynamicStruct.sol');
var InitMemoryArrayFixedSize = artifacts.require('./InitMemoryArrayFixedSize.sol');
var InitMemoryArrayFixedSizeMulti = artifacts.require('./InitMemoryArrayFixedSizeMulti.sol');
var InitMemoryArrayFixedSizeStruct = artifacts.require('./InitMemoryArrayFixedSizeStruct.sol');
var InitStorageArrayDynamic = artifacts.require('./InitStorageArrayDynamic.sol');
var InitStorageArrayDynamicMapping = artifacts.require('./InitStorageArrayDynamicMapping.sol');
var InitStorageArrayDynamicMulti = artifacts.require('./InitStorageArrayDynamicMulti.sol');
var InitStorageArrayDynamicStruct = artifacts.require('./InitStorageArrayDynamicStruct.sol');
var InitStorageArrayFixedMapping = artifacts.require('./InitStorageArrayFixedMapping.sol');
var InitStorageArrayFixedSize = artifacts.require('./InitStorageArrayFixedSize.sol');
var InitStorageArrayFixedSizeMulti = artifacts.require('./InitStorageArrayFixedSizeMulti.sol');
var InitStorageArrayFixedSizeStruct = artifacts.require('./InitStorageArrayFixedSizeStruct.sol');
var InitStorageMapping = artifacts.require('./InitStorageMapping.sol');
var InitStorageMappingArray = artifacts.require('./InitStorageMappingArray.sol');
var InitStorageMappingNested = artifacts.require('./InitStorageMappingNested.sol');
var InitStorageMappingStruct = artifacts.require('./InitStorageMappingStruct.sol');
var ArrayFixedSizeStorageNoAliasBase = artifacts.require('./ArrayFixedSizeStorageNoAliasBase.sol');
var ArrayFixedSizeStorageNoAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeStorageNoAliasSubArrayFixedSize.sol');
var ArrayFixedSizeStorageNoAliasSubMapping = artifacts.require('./ArrayFixedSizeStorageNoAliasSubMapping.sol');
var ArrayFixedSizeStorageNoAliasSubStruct = artifacts.require('./ArrayFixedSizeStorageNoAliasSubStruct.sol');
var MappingArrayFixedSizeStorageNoAliasBase = artifacts.require('./MappingArrayFixedSizeStorageNoAliasBase.sol');
var MappingArrayFixedSizeStorageNoAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeStorageNoAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeStorageNoAliasSubStruct = artifacts.require('./MappingArrayFixedSizeStorageNoAliasSubStruct.sol');
var MappingStorageNoAliasBase = artifacts.require('./MappingStorageNoAliasBase.sol');
var MappingStorageNoAliasSubArrayFixedSize = artifacts.require('./MappingStorageNoAliasSubArrayFixedSize.sol');
var MappingStorageNoAliasSubMapping = artifacts.require('./MappingStorageNoAliasSubMapping.sol');
var MappingStorageNoAliasSubStruct = artifacts.require('./MappingStorageNoAliasSubStruct.sol');
var MappingStructStorageNoAliasBase = artifacts.require('./MappingStructStorageNoAliasBase.sol');
var MappingStructStorageNoAliasSubArrayFixedSize = artifacts.require('./MappingStructStorageNoAliasSubArrayFixedSize.sol');
var MappingStructStorageNoAliasSubMapping = artifacts.require('./MappingStructStorageNoAliasSubMapping.sol');
var MappingStructStorageNoAliasSubStruct = artifacts.require('./MappingStructStorageNoAliasSubStruct.sol');
var StructArrayFixedSizeStorageNoAliasBase = artifacts.require('./StructArrayFixedSizeStorageNoAliasBase.sol');
var StructArrayFixedSizeStorageNoAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeStorageNoAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeStorageNoAliasSubMapping = artifacts.require('./StructArrayFixedSizeStorageNoAliasSubMapping.sol');
var StructArrayFixedSizeStorageNoAliasSubStruct = artifacts.require('./StructArrayFixedSizeStorageNoAliasSubStruct.sol');
var StructMappingStorageNoAliasBase = artifacts.require('./StructMappingStorageNoAliasBase.sol');
var StructMappingStorageNoAliasSubArrayFixedSize = artifacts.require('./StructMappingStorageNoAliasSubArrayFixedSize.sol');
var StructMappingStorageNoAliasSubMapping = artifacts.require('./StructMappingStorageNoAliasSubMapping.sol');
var StructMappingStorageNoAliasSubStruct = artifacts.require('./StructMappingStorageNoAliasSubStruct.sol');
var StructStorageNoAliasBase = artifacts.require('./StructStorageNoAliasBase.sol');
var StructStorageNoAliasSubArrayFixedSize = artifacts.require('./StructStorageNoAliasSubArrayFixedSize.sol');
var StructStorageNoAliasSubMapping = artifacts.require('./StructStorageNoAliasSubMapping.sol');
var StructStorageNoAliasSubStruct = artifacts.require('./StructStorageNoAliasSubStruct.sol');
var ArrayFixedSizeLibraryStorageAliasBase = artifacts.require('./ArrayFixedSizeLibraryStorageAliasBase.sol');
var ArrayFixedSizeLibraryStorageAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeLibraryStorageAliasSubArrayFixedSize.sol');
var ArrayFixedSizeLibraryStorageAliasSubMapping = artifacts.require('./ArrayFixedSizeLibraryStorageAliasSubMapping.sol');
var ArrayFixedSizeLibraryStorageAliasSubStruct = artifacts.require('./ArrayFixedSizeLibraryStorageAliasSubStruct.sol');
var ArrayFixedSizeLibraryStorageNoAliasBase = artifacts.require('./ArrayFixedSizeLibraryStorageNoAliasBase.sol');
var ArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize.sol');
var ArrayFixedSizeLibraryStorageNoAliasSubMapping = artifacts.require('./ArrayFixedSizeLibraryStorageNoAliasSubMapping.sol');
var ArrayFixedSizeLibraryStorageNoAliasSubStruct = artifacts.require('./ArrayFixedSizeLibraryStorageNoAliasSubStruct.sol');
var ArrayFixedSizeStorageArgumentAliasBase = artifacts.require('./ArrayFixedSizeStorageArgumentAliasBase.sol');
var ArrayFixedSizeStorageArgumentAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeStorageArgumentAliasSubArrayFixedSize.sol');
var ArrayFixedSizeStorageArgumentAliasSubMapping = artifacts.require('./ArrayFixedSizeStorageArgumentAliasSubMapping.sol');
var ArrayFixedSizeStorageArgumentAliasSubStruct = artifacts.require('./ArrayFixedSizeStorageArgumentAliasSubStruct.sol');
var ArrayFixedSizeStorageArgumentNoAliasBase = artifacts.require('./ArrayFixedSizeStorageArgumentNoAliasBase.sol');
var ArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize.sol');
var ArrayFixedSizeStorageArgumentNoAliasSubMapping = artifacts.require('./ArrayFixedSizeStorageArgumentNoAliasSubMapping.sol');
var ArrayFixedSizeStorageArgumentNoAliasSubStruct = artifacts.require('./ArrayFixedSizeStorageArgumentNoAliasSubStruct.sol');
var ArrayFixedSizeStoragePointerAlias = artifacts.require('./ArrayFixedSizeStoragePointerAlias.sol');
var ArrayFixedSizeStoragePointerAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeStoragePointerAliasSubArrayFixedSize.sol');
var ArrayFixedSizeStoragePointerAliasSubMapping = artifacts.require('./ArrayFixedSizeStoragePointerAliasSubMapping.sol');
var ArrayFixedSizeStoragePointerAliasSubStruct = artifacts.require('./ArrayFixedSizeStoragePointerAliasSubStruct.sol');
var ArrayFixedSizeStoragePointerArrayPop = artifacts.require('./ArrayFixedSizeStoragePointerArrayPop.sol');
var ArrayFixedSizeStoragePointerNoAliasBase = artifacts.require('./ArrayFixedSizeStoragePointerNoAliasBase.sol');
var ArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./ArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize.sol');
var ArrayFixedSizeStoragePointerNoAliasSubMapping = artifacts.require('./ArrayFixedSizeStoragePointerNoAliasSubMapping.sol');
var ArrayFixedSizeStoragePointerNoAliasSubStruct = artifacts.require('./ArrayFixedSizeStoragePointerNoAliasSubStruct.sol');
var MappingArrayFixedSizeLibraryStorageAliasBase = artifacts.require('./MappingArrayFixedSizeLibraryStorageAliasBase.sol');
var MappingArrayFixedSizeLibraryStorageAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeLibraryStorageAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeLibraryStorageAliasSubMapping = artifacts.require('./MappingArrayFixedSizeLibraryStorageAliasSubMapping.sol');
var MappingArrayFixedSizeLibraryStorageAliasSubStruct = artifacts.require('./MappingArrayFixedSizeLibraryStorageAliasSubStruct.sol');
var MappingArrayFixedSizeLibraryStorageNoAliasBase = artifacts.require('./MappingArrayFixedSizeLibraryStorageNoAliasBase.sol');
var MappingArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeLibraryStorageNoAliasSubMapping = artifacts.require('./MappingArrayFixedSizeLibraryStorageNoAliasSubMapping.sol');
var MappingArrayFixedSizeLibraryStorageNoAliasSubStruct = artifacts.require('./MappingArrayFixedSizeLibraryStorageNoAliasSubStruct.sol');
var MappingArrayFixedSizeStorageArgumentAliasBase = artifacts.require('./MappingArrayFixedSizeStorageArgumentAliasBase.sol');
var MappingArrayFixedSizeStorageArgumentAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeStorageArgumentAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeStorageArgumentAliasSubMapping = artifacts.require('./MappingArrayFixedSizeStorageArgumentAliasSubMapping.sol');
var MappingArrayFixedSizeStorageArgumentAliasSubStruct = artifacts.require('./MappingArrayFixedSizeStorageArgumentAliasSubStruct.sol');
var MappingArrayFixedSizeStorageArgumentNoAliasBase = artifacts.require('./MappingArrayFixedSizeStorageArgumentNoAliasBase.sol');
var MappingArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeStorageArgumentNoAliasSubStruct = artifacts.require('./MappingArrayFixedSizeStorageArgumentNoAliasSubStruct.sol');
var MappingArrayFixedSizeStoragePointerAlias = artifacts.require('./MappingArrayFixedSizeStoragePointerAlias.sol');
var MappingArrayFixedSizeStoragePointerAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeStoragePointerAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeStoragePointerAliasSubMapping = artifacts.require('./MappingArrayFixedSizeStoragePointerAliasSubMapping.sol');
var MappingArrayFixedSizeStoragePointerAliasSubStruct = artifacts.require('./MappingArrayFixedSizeStoragePointerAliasSubStruct.sol');
var MappingArrayFixedSizeStoragePointerNoAliasBase = artifacts.require('./MappingArrayFixedSizeStoragePointerNoAliasBase.sol');
var MappingArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./MappingArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize.sol');
var MappingArrayFixedSizeStoragePointerNoAliasSubMapping = artifacts.require('./MappingArrayFixedSizeStoragePointerNoAliasSubMapping.sol');
var MappingArrayFixedSizeStoragePointerNoAliasSubStruct = artifacts.require('./MappingArrayFixedSizeStoragePointerNoAliasSubStruct.sol');
var MappingLibraryStorageAliasBase = artifacts.require('./MappingLibraryStorageAliasBase.sol');
var MappingLibraryStorageAliasSubArrayFixedSize = artifacts.require('./MappingLibraryStorageAliasSubArrayFixedSize.sol');
var MappingLibraryStorageAliasSubMapping = artifacts.require('./MappingLibraryStorageAliasSubMapping.sol');
var MappingLibraryStorageAliasSubStruct = artifacts.require('./MappingLibraryStorageAliasSubStruct.sol');
var MappingLibraryStorageNoAliasBase = artifacts.require('./MappingLibraryStorageNoAliasBase.sol');
var MappingLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./MappingLibraryStorageNoAliasSubArrayFixedSize.sol');
var MappingLibraryStorageNoAliasSubMapping = artifacts.require('./MappingLibraryStorageNoAliasSubMapping.sol');
var MappingLibraryStorageNoAliasSubStruct = artifacts.require('./MappingLibraryStorageNoAliasSubStruct.sol');
var MappingStorageArgumentAliasBase = artifacts.require('./MappingStorageArgumentAliasBase.sol');
var MappingStorageArgumentAliasSubArrayFixedSize = artifacts.require('./MappingStorageArgumentAliasSubArrayFixedSize.sol');
var MappingStorageArgumentAliasSubMapping = artifacts.require('./MappingStorageArgumentAliasSubMapping.sol');
var MappingStorageArgumentAliasSubStruct = artifacts.require('./MappingStorageArgumentAliasSubStruct.sol');
var MappingStorageArgumentNoAliasBase = artifacts.require('./MappingStorageArgumentNoAliasBase.sol');
var MappingStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./MappingStorageArgumentNoAliasSubArrayFixedSize.sol');
var MappingStorageArgumentNoAliasSubStruct = artifacts.require('./MappingStorageArgumentNoAliasSubStruct.sol');
var MappingStoragePointerAlias = artifacts.require('./MappingStoragePointerAlias.sol');
var MappingStoragePointerAliasSubArrayFixedSize = artifacts.require('./MappingStoragePointerAliasSubArrayFixedSize.sol');
var MappingStoragePointerAliasSubMapping = artifacts.require('./MappingStoragePointerAliasSubMapping.sol');
var MappingStoragePointerAliasSubStruct = artifacts.require('./MappingStoragePointerAliasSubStruct.sol');
var MappingStoragePointerNoAliasBase = artifacts.require('./MappingStoragePointerNoAliasBase.sol');
var MappingStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./MappingStoragePointerNoAliasSubArrayFixedSize.sol');
var MappingStoragePointerNoAliasSubMapping = artifacts.require('./MappingStoragePointerNoAliasSubMapping.sol');
var MappingStoragePointerNoAliasSubStruct = artifacts.require('./MappingStoragePointerNoAliasSubStruct.sol');
var MappingStructLibraryStorageAliasBase = artifacts.require('./MappingStructLibraryStorageAliasBase.sol');
var MappingStructLibraryStorageAliasSubArrayFixedSize = artifacts.require('./MappingStructLibraryStorageAliasSubArrayFixedSize.sol');
var MappingStructLibraryStorageAliasSubMapping = artifacts.require('./MappingStructLibraryStorageAliasSubMapping.sol');
var MappingStructLibraryStorageAliasSubStruct = artifacts.require('./MappingStructLibraryStorageAliasSubStruct.sol');
var MappingStructLibraryStorageNoAliasBase = artifacts.require('./MappingStructLibraryStorageNoAliasBase.sol');
var MappingStructLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./MappingStructLibraryStorageNoAliasSubArrayFixedSize.sol');
var MappingStructLibraryStorageNoAliasSubMapping = artifacts.require('./MappingStructLibraryStorageNoAliasSubMapping.sol');
var MappingStructLibraryStorageNoAliasSubStruct = artifacts.require('./MappingStructLibraryStorageNoAliasSubStruct.sol');
var MappingStructStorageArgumentAliasBase = artifacts.require('./MappingStructStorageArgumentAliasBase.sol');
var MappingStructStorageArgumentAliasSubArrayFixedSize = artifacts.require('./MappingStructStorageArgumentAliasSubArrayFixedSize.sol');
var MappingStructStorageArgumentAliasSubMapping = artifacts.require('./MappingStructStorageArgumentAliasSubMapping.sol');
var MappingStructStorageArgumentAliasSubStruct = artifacts.require('./MappingStructStorageArgumentAliasSubStruct.sol');
var MappingStructStorageArgumentNoAliasBase = artifacts.require('./MappingStructStorageArgumentNoAliasBase.sol');
var MappingStructStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./MappingStructStorageArgumentNoAliasSubArrayFixedSize.sol');
var MappingStructStorageArgumentNoAliasSubStruct = artifacts.require('./MappingStructStorageArgumentNoAliasSubStruct.sol');
var MappingStructStoragePointerAlias = artifacts.require('./MappingStructStoragePointerAlias.sol');
var MappingStructStoragePointerAliasSubArrayFixedSize = artifacts.require('./MappingStructStoragePointerAliasSubArrayFixedSize.sol');
var MappingStructStoragePointerAliasSubMapping = artifacts.require('./MappingStructStoragePointerAliasSubMapping.sol');
var MappingStructStoragePointerAliasSubStruct = artifacts.require('./MappingStructStoragePointerAliasSubStruct.sol');
var MappingStructStoragePointerNoAliasBase = artifacts.require('./MappingStructStoragePointerNoAliasBase.sol');
var MappingStructStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./MappingStructStoragePointerNoAliasSubArrayFixedSize.sol');
var MappingStructStoragePointerNoAliasSubMapping = artifacts.require('./MappingStructStoragePointerNoAliasSubMapping.sol');
var MappingStructStoragePointerNoAliasSubStruct = artifacts.require('./MappingStructStoragePointerNoAliasSubStruct.sol');
var StructArrayFixedSizeLibraryStorageAliasBase = artifacts.require('./StructArrayFixedSizeLibraryStorageAliasBase.sol');
var StructArrayFixedSizeLibraryStorageAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeLibraryStorageAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeLibraryStorageAliasSubMapping = artifacts.require('./StructArrayFixedSizeLibraryStorageAliasSubMapping.sol');
var StructArrayFixedSizeLibraryStorageAliasSubStruct = artifacts.require('./StructArrayFixedSizeLibraryStorageAliasSubStruct.sol');
var StructArrayFixedSizeLibraryStorageNoAliasBase = artifacts.require('./StructArrayFixedSizeLibraryStorageNoAliasBase.sol');
var StructArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeLibraryStorageNoAliasSubMapping = artifacts.require('./StructArrayFixedSizeLibraryStorageNoAliasSubMapping.sol');
var StructArrayFixedSizeLibraryStorageNoAliasSubStruct = artifacts.require('./StructArrayFixedSizeLibraryStorageNoAliasSubStruct.sol');
var StructArrayFixedSizeStorageArgumentAliasBase = artifacts.require('./StructArrayFixedSizeStorageArgumentAliasBase.sol');
var StructArrayFixedSizeStorageArgumentAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeStorageArgumentAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeStorageArgumentAliasSubMapping = artifacts.require('./StructArrayFixedSizeStorageArgumentAliasSubMapping.sol');
var StructArrayFixedSizeStorageArgumentAliasSubStruct = artifacts.require('./StructArrayFixedSizeStorageArgumentAliasSubStruct.sol');
var StructArrayFixedSizeStorageArgumentNoAliasBase = artifacts.require('./StructArrayFixedSizeStorageArgumentNoAliasBase.sol');
var StructArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeStorageArgumentNoAliasSubStruct = artifacts.require('./StructArrayFixedSizeStorageArgumentNoAliasSubStruct.sol');
var StructArrayFixedSizeStoragePointerAlias = artifacts.require('./StructArrayFixedSizeStoragePointerAlias.sol');
var StructArrayFixedSizeStoragePointerAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeStoragePointerAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeStoragePointerAliasSubMapping = artifacts.require('./StructArrayFixedSizeStoragePointerAliasSubMapping.sol');
var StructArrayFixedSizeStoragePointerAliasSubStruct = artifacts.require('./StructArrayFixedSizeStoragePointerAliasSubStruct.sol');
var StructArrayFixedSizeStoragePointerArrayPop = artifacts.require('./StructArrayFixedSizeStoragePointerArrayPop.sol');
var StructArrayFixedSizeStoragePointerNoAliasBase = artifacts.require('./StructArrayFixedSizeStoragePointerNoAliasBase.sol');
var StructArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./StructArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize.sol');
var StructArrayFixedSizeStoragePointerNoAliasSubMapping = artifacts.require('./StructArrayFixedSizeStoragePointerNoAliasSubMapping.sol');
var StructArrayFixedSizeStoragePointerNoAliasSubStruct = artifacts.require('./StructArrayFixedSizeStoragePointerNoAliasSubStruct.sol');
var StructLibraryStorageAliasBase = artifacts.require('./StructLibraryStorageAliasBase.sol');
var StructLibraryStorageAliasSubArrayFixedSize = artifacts.require('./StructLibraryStorageAliasSubArrayFixedSize.sol');
var StructLibraryStorageAliasSubMapping = artifacts.require('./StructLibraryStorageAliasSubMapping.sol');
var StructLibraryStorageAliasSubStruct = artifacts.require('./StructLibraryStorageAliasSubStruct.sol');
var StructLibraryStorageNoAliasBase = artifacts.require('./StructLibraryStorageNoAliasBase.sol');
var StructLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./StructLibraryStorageNoAliasSubArrayFixedSize.sol');
var StructLibraryStorageNoAliasSubMapping = artifacts.require('./StructLibraryStorageNoAliasSubMapping.sol');
var StructLibraryStorageNoAliasSubStruct = artifacts.require('./StructLibraryStorageNoAliasSubStruct.sol');
var StructMappingLibraryStorageAliasBase = artifacts.require('./StructMappingLibraryStorageAliasBase.sol');
var StructMappingLibraryStorageAliasSubArrayFixedSize = artifacts.require('./StructMappingLibraryStorageAliasSubArrayFixedSize.sol');
var StructMappingLibraryStorageAliasSubMapping = artifacts.require('./StructMappingLibraryStorageAliasSubMapping.sol');
var StructMappingLibraryStorageAliasSubStruct = artifacts.require('./StructMappingLibraryStorageAliasSubStruct.sol');
var StructMappingLibraryStorageNoAliasBase = artifacts.require('./StructMappingLibraryStorageNoAliasBase.sol');
var StructMappingLibraryStorageNoAliasSubArrayFixedSize = artifacts.require('./StructMappingLibraryStorageNoAliasSubArrayFixedSize.sol');
var StructMappingLibraryStorageNoAliasSubMapping = artifacts.require('./StructMappingLibraryStorageNoAliasSubMapping.sol');
var StructMappingLibraryStorageNoAliasSubStruct = artifacts.require('./StructMappingLibraryStorageNoAliasSubStruct.sol');
var StructMappingStorageArgumentAliasBase = artifacts.require('./StructMappingStorageArgumentAliasBase.sol');
var StructMappingStorageArgumentAliasSubArrayFixedSize = artifacts.require('./StructMappingStorageArgumentAliasSubArrayFixedSize.sol');
var StructMappingStorageArgumentAliasSubMapping = artifacts.require('./StructMappingStorageArgumentAliasSubMapping.sol');
var StructMappingStorageArgumentAliasSubStruct = artifacts.require('./StructMappingStorageArgumentAliasSubStruct.sol');
var StructMappingStorageArgumentNoAliasBase = artifacts.require('./StructMappingStorageArgumentNoAliasBase.sol');
var StructMappingStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./StructMappingStorageArgumentNoAliasSubArrayFixedSize.sol');
var StructMappingStorageArgumentNoAliasSubStruct = artifacts.require('./StructMappingStorageArgumentNoAliasSubStruct.sol');
var StructMappingStoragePointerAlias = artifacts.require('./StructMappingStoragePointerAlias.sol');
var StructMappingStoragePointerAliasSubArrayFixedSize = artifacts.require('./StructMappingStoragePointerAliasSubArrayFixedSize.sol');
var StructMappingStoragePointerAliasSubMapping = artifacts.require('./StructMappingStoragePointerAliasSubMapping.sol');
var StructMappingStoragePointerAliasSubStruct = artifacts.require('./StructMappingStoragePointerAliasSubStruct.sol');
var StructMappingStoragePointerNoAliasBase = artifacts.require('./StructMappingStoragePointerNoAliasBase.sol');
var StructMappingStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./StructMappingStoragePointerNoAliasSubArrayFixedSize.sol');
var StructMappingStoragePointerNoAliasSubMapping = artifacts.require('./StructMappingStoragePointerNoAliasSubMapping.sol');
var StructMappingStoragePointerNoAliasSubStruct = artifacts.require('./StructMappingStoragePointerNoAliasSubStruct.sol');
var StructStorageArgumentAliasBase = artifacts.require('./StructStorageArgumentAliasBase.sol');
var StructStorageArgumentAliasSubArrayFixedSize = artifacts.require('./StructStorageArgumentAliasSubArrayFixedSize.sol');
var StructStorageArgumentAliasSubStruct = artifacts.require('./StructStorageArgumentAliasSubStruct.sol');
var StructStorageArgumentNoAliasBase = artifacts.require('./StructStorageArgumentNoAliasBase.sol');
var StructStorageArgumentNoAliasSubArrayFixedSize = artifacts.require('./StructStorageArgumentNoAliasSubArrayFixedSize.sol');
var StructStorageArgumentNoAliasSubStruct = artifacts.require('./StructStorageArgumentNoAliasSubStruct.sol');
var StructStoragePointerAlias = artifacts.require('./StructStoragePointerAlias.sol');
var StructStoragePointerAliasSubArrayFixedSize = artifacts.require('./StructStoragePointerAliasSubArrayFixedSize.sol');
var StructStoragePointerAliasSubMapping = artifacts.require('./StructStoragePointerAliasSubMapping.sol');
var StructStoragePointerAliasSubStruct = artifacts.require('./StructStoragePointerAliasSubStruct.sol');
var StructStoragePointerArrayPop = artifacts.require('./StructStoragePointerArrayPop.sol');
var StructStoragePointerNoAliasBase = artifacts.require('./StructStoragePointerNoAliasBase.sol');
var StructStoragePointerNoAliasSubArrayFixedSize = artifacts.require('./StructStoragePointerNoAliasSubArrayFixedSize.sol');
var StructStoragePointerNoAliasSubMapping = artifacts.require('./StructStoragePointerNoAliasSubMapping.sol');
var StructStoragePointerNoAliasSubStruct = artifacts.require('./StructStoragePointerNoAliasSubStruct.sol');

module.exports = function(deployer) {
  deployer.deploy(AssignArrayDynamicL2L);
  deployer.deploy(AssignArrayDynamicL2M);
  deployer.deploy(AssignArrayDynamicL2S);
  deployer.deploy(AssignArrayDynamicM2L);
  deployer.deploy(AssignArrayDynamicM2M);
  deployer.deploy(AssignArrayDynamicM2S);
  deployer.deploy(AssignArrayDynamicMultiL2L);
  deployer.deploy(AssignArrayDynamicMultiL2M);
  deployer.deploy(AssignArrayDynamicMultiL2S);
  deployer.deploy(AssignArrayDynamicMultiM2L);
  deployer.deploy(AssignArrayDynamicMultiM2M);
  deployer.deploy(AssignArrayDynamicMultiM2S);
  deployer.deploy(AssignArrayDynamicMultiS2L);
  deployer.deploy(AssignArrayDynamicMultiS2M);
  deployer.deploy(AssignArrayDynamicMultiS2S);
  deployer.deploy(AssignArrayDynamicS2L);
  deployer.deploy(AssignArrayDynamicS2M);
  deployer.deploy(AssignArrayDynamicS2S);
  deployer.deploy(AssignArrayDynamicStructL2L);
  deployer.deploy(AssignArrayDynamicStructL2M);
  deployer.deploy(AssignArrayDynamicStructL2S);
  deployer.deploy(AssignArrayDynamicStructM2M);
  deployer.deploy(AssignArrayDynamicStructS2L);
  deployer.deploy(AssignArrayDynamicStructS2M);
  deployer.deploy(AssignArrayDynamicStructS2S);
  deployer.deploy(AssignArrayFixedSizeL2L);
  deployer.deploy(AssignArrayFixedSizeL2M);
  deployer.deploy(AssignArrayFixedSizeL2S);
  deployer.deploy(AssignArrayFixedSizeM2L);
  deployer.deploy(AssignArrayFixedSizeM2M);
  deployer.deploy(AssignArrayFixedSizeM2S);
  deployer.deploy(AssignArrayFixedSizeMappingL2L);
  deployer.deploy(AssignArrayFixedSizeMappingL2S);
  deployer.deploy(AssignArrayFixedSizeMappingS2L);
  deployer.deploy(AssignArrayFixedSizeMappingS2S);
  deployer.deploy(AssignArrayFixedSizeMultiL2L);
  deployer.deploy(AssignArrayFixedSizeMultiL2M);
  deployer.deploy(AssignArrayFixedSizeMultiL2S);
  deployer.deploy(AssignArrayFixedSizeMultiM2L);
  deployer.deploy(AssignArrayFixedSizeMultiM2M);
  deployer.deploy(AssignArrayFixedSizeMultiM2S);
  deployer.deploy(AssignArrayFixedSizeMultiS2L);
  deployer.deploy(AssignArrayFixedSizeMultiS2M);
  deployer.deploy(AssignArrayFixedSizeMultiS2S);
  deployer.deploy(AssignArrayFixedSizeS2L);
  deployer.deploy(AssignArrayFixedSizeS2M);
  deployer.deploy(AssignArrayFixedSizeS2S);
  deployer.deploy(AssignArrayFixedSizeStructL2L);
  deployer.deploy(AssignArrayFixedSizeStructL2M);
  deployer.deploy(AssignArrayFixedSizeStructL2S);
  deployer.deploy(AssignArrayFixedSizeStructM2M);
  deployer.deploy(AssignArrayFixedSizeStructS2L);
  deployer.deploy(AssignArrayFixedSizeStructS2M);
  deployer.deploy(AssignArrayFixedSizeStructS2S);
  deployer.deploy(AssignMappingArrayL2L);
  deployer.deploy(AssignMappingArrayS2L);
  deployer.deploy(AssignMappingL2L);
  deployer.deploy(AssignMappingNestedL2L);
  deployer.deploy(AssignMappingNestedS2L);
  deployer.deploy(AssignMappingS2L);
  deployer.deploy(AssignMappingStructL2L);
  deployer.deploy(AssignMappingStructS2L);
  deployer.deploy(AssignStructArrayDynamicL2L);
  deployer.deploy(AssignStructArrayDynamicL2S);
  deployer.deploy(AssignStructArrayDynamicMultiL2L);
  deployer.deploy(AssignStructArrayDynamicMultiL2S);
  deployer.deploy(AssignStructArrayDynamicMultiS2L);
  deployer.deploy(AssignStructArrayDynamicMultiS2S);
  deployer.deploy(AssignStructArrayDynamicS2L);
  deployer.deploy(AssignStructArrayDynamicS2S);
  deployer.deploy(AssignStructArrayFixedSizeL2L);
  deployer.deploy(AssignStructArrayFixedSizeL2M);
  deployer.deploy(AssignStructArrayFixedSizeL2S);
  deployer.deploy(AssignStructArrayFixedSizeM2L);
  deployer.deploy(AssignStructArrayFixedSizeM2M);
  deployer.deploy(AssignStructArrayFixedSizeM2S);
  deployer.deploy(AssignStructArrayFixedSizeMultiL2L);
  deployer.deploy(AssignStructArrayFixedSizeMultiL2M);
  deployer.deploy(AssignStructArrayFixedSizeMultiL2S);
  deployer.deploy(AssignStructArrayFixedSizeMultiM2L);
  deployer.deploy(AssignStructArrayFixedSizeMultiM2M);
  deployer.deploy(AssignStructArrayFixedSizeMultiM2S);
  deployer.deploy(AssignStructArrayFixedSizeMultiS2L);
  deployer.deploy(AssignStructArrayFixedSizeMultiS2M);
  deployer.deploy(AssignStructArrayFixedSizeMultiS2S);
  deployer.deploy(AssignStructArrayFixedSizeS2L);
  deployer.deploy(AssignStructArrayFixedSizeS2M);
  deployer.deploy(AssignStructArrayFixedSizeS2S);
  deployer.deploy(AssignStructMappingL2L);
  deployer.deploy(AssignStructMappingL2S);
  deployer.deploy(AssignStructMappingS2L);
  deployer.deploy(AssignStructMappingS2S);
  deployer.deploy(DeleteMemoryArrayDynamic);
  deployer.deploy(DeleteMemoryArrayDynamicMulti);
  deployer.deploy(DeleteMemoryArrayDynamicStruct);
  deployer.deploy(DeleteMemoryArrayFixedSize);
  deployer.deploy(DeleteMemoryArrayFixedSizeMulti);
  deployer.deploy(DeleteMemoryArrayFixedSizeStruct);
  deployer.deploy(DeleteStorageArrayDynamic);
  deployer.deploy(DeleteStorageArrayDynamicMulti);
  deployer.deploy(DeleteStorageArrayDynamicStruct);
  deployer.deploy(DeleteStorageArrayFixedMapping);
  deployer.deploy(DeleteStorageArrayFixedSize);
  deployer.deploy(DeleteStorageArrayFixedSizeMulti);
  deployer.deploy(DeleteStorageArrayFixedSizeStruct);
  deployer.deploy(DeleteValueTypes);
  deployer.deploy(InitMemoryArrayDynamic);
  deployer.deploy(InitMemoryArrayDynamicMulti);
  deployer.deploy(InitMemoryArrayDynamicStruct);
  deployer.deploy(InitMemoryArrayFixedSize);
  deployer.deploy(InitMemoryArrayFixedSizeMulti);
  deployer.deploy(InitMemoryArrayFixedSizeStruct);
  deployer.deploy(InitStorageArrayDynamic);
  deployer.deploy(InitStorageArrayDynamicMapping);
  deployer.deploy(InitStorageArrayDynamicMulti);
  deployer.deploy(InitStorageArrayDynamicStruct);
  deployer.deploy(InitStorageArrayFixedMapping);
  deployer.deploy(InitStorageArrayFixedSize);
  deployer.deploy(InitStorageArrayFixedSizeMulti);
  deployer.deploy(InitStorageArrayFixedSizeStruct);
  deployer.deploy(InitStorageMapping);
  deployer.deploy(InitStorageMappingArray);
  deployer.deploy(InitStorageMappingNested);
  deployer.deploy(InitStorageMappingStruct);
  deployer.deploy(ArrayFixedSizeStorageNoAliasBase);
  deployer.deploy(ArrayFixedSizeStorageNoAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeStorageNoAliasSubMapping);
  deployer.deploy(ArrayFixedSizeStorageNoAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeStorageNoAliasBase);
  deployer.deploy(MappingArrayFixedSizeStorageNoAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeStorageNoAliasSubStruct);
  deployer.deploy(MappingStorageNoAliasBase);
  deployer.deploy(MappingStorageNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStorageNoAliasSubMapping);
  deployer.deploy(MappingStorageNoAliasSubStruct);
  deployer.deploy(MappingStructStorageNoAliasBase);
  deployer.deploy(MappingStructStorageNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStructStorageNoAliasSubMapping);
  deployer.deploy(MappingStructStorageNoAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeStorageNoAliasBase);
  deployer.deploy(StructArrayFixedSizeStorageNoAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeStorageNoAliasSubMapping);
  deployer.deploy(StructArrayFixedSizeStorageNoAliasSubStruct);
  deployer.deploy(StructMappingStorageNoAliasBase);
  deployer.deploy(StructMappingStorageNoAliasSubArrayFixedSize);
  deployer.deploy(StructMappingStorageNoAliasSubMapping);
  deployer.deploy(StructMappingStorageNoAliasSubStruct);
  deployer.deploy(StructStorageNoAliasBase);
  deployer.deploy(StructStorageNoAliasSubArrayFixedSize);
  deployer.deploy(StructStorageNoAliasSubMapping);
  deployer.deploy(StructStorageNoAliasSubStruct);
  deployer.deploy(ArrayFixedSizeLibraryStorageAliasBase);
  deployer.deploy(ArrayFixedSizeLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeLibraryStorageAliasSubMapping);
  deployer.deploy(ArrayFixedSizeLibraryStorageAliasSubStruct);
  deployer.deploy(ArrayFixedSizeLibraryStorageNoAliasBase);
  deployer.deploy(ArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeLibraryStorageNoAliasSubMapping);
  deployer.deploy(ArrayFixedSizeLibraryStorageNoAliasSubStruct);
  deployer.deploy(ArrayFixedSizeStorageArgumentAliasBase);
  deployer.deploy(ArrayFixedSizeStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeStorageArgumentAliasSubMapping);
  deployer.deploy(ArrayFixedSizeStorageArgumentAliasSubStruct);
  deployer.deploy(ArrayFixedSizeStorageArgumentNoAliasBase);
  deployer.deploy(ArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeStorageArgumentNoAliasSubMapping);
  deployer.deploy(ArrayFixedSizeStorageArgumentNoAliasSubStruct);
  deployer.deploy(ArrayFixedSizeStoragePointerAlias);
  deployer.deploy(ArrayFixedSizeStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeStoragePointerAliasSubMapping);
  deployer.deploy(ArrayFixedSizeStoragePointerAliasSubStruct);
  deployer.deploy(ArrayFixedSizeStoragePointerArrayPop);
  deployer.deploy(ArrayFixedSizeStoragePointerNoAliasBase);
  deployer.deploy(ArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(ArrayFixedSizeStoragePointerNoAliasSubMapping);
  deployer.deploy(ArrayFixedSizeStoragePointerNoAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageAliasBase);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageAliasSubMapping);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageNoAliasBase);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageNoAliasSubMapping);
  deployer.deploy(MappingArrayFixedSizeLibraryStorageNoAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentAliasBase);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentAliasSubMapping);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentNoAliasBase);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeStorageArgumentNoAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeStoragePointerAlias);
  deployer.deploy(MappingArrayFixedSizeStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeStoragePointerAliasSubMapping);
  deployer.deploy(MappingArrayFixedSizeStoragePointerAliasSubStruct);
  deployer.deploy(MappingArrayFixedSizeStoragePointerNoAliasBase);
  deployer.deploy(MappingArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(MappingArrayFixedSizeStoragePointerNoAliasSubMapping);
  deployer.deploy(MappingArrayFixedSizeStoragePointerNoAliasSubStruct);
  deployer.deploy(MappingLibraryStorageAliasBase);
  deployer.deploy(MappingLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(MappingLibraryStorageAliasSubMapping);
  deployer.deploy(MappingLibraryStorageAliasSubStruct);
  deployer.deploy(MappingLibraryStorageNoAliasBase);
  deployer.deploy(MappingLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(MappingLibraryStorageNoAliasSubMapping);
  deployer.deploy(MappingLibraryStorageNoAliasSubStruct);
  deployer.deploy(MappingStorageArgumentAliasBase);
  deployer.deploy(MappingStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(MappingStorageArgumentAliasSubMapping);
  deployer.deploy(MappingStorageArgumentAliasSubStruct);
  deployer.deploy(MappingStorageArgumentNoAliasBase);
  deployer.deploy(MappingStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStorageArgumentNoAliasSubStruct);
  deployer.deploy(MappingStoragePointerAlias);
  deployer.deploy(MappingStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(MappingStoragePointerAliasSubMapping);
  deployer.deploy(MappingStoragePointerAliasSubStruct);
  deployer.deploy(MappingStoragePointerNoAliasBase);
  deployer.deploy(MappingStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStoragePointerNoAliasSubMapping);
  deployer.deploy(MappingStoragePointerNoAliasSubStruct);
  deployer.deploy(MappingStructLibraryStorageAliasBase);
  deployer.deploy(MappingStructLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(MappingStructLibraryStorageAliasSubMapping);
  deployer.deploy(MappingStructLibraryStorageAliasSubStruct);
  deployer.deploy(MappingStructLibraryStorageNoAliasBase);
  deployer.deploy(MappingStructLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStructLibraryStorageNoAliasSubMapping);
  deployer.deploy(MappingStructLibraryStorageNoAliasSubStruct);
  deployer.deploy(MappingStructStorageArgumentAliasBase);
  deployer.deploy(MappingStructStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(MappingStructStorageArgumentAliasSubMapping);
  deployer.deploy(MappingStructStorageArgumentAliasSubStruct);
  deployer.deploy(MappingStructStorageArgumentNoAliasBase);
  deployer.deploy(MappingStructStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStructStorageArgumentNoAliasSubStruct);
  deployer.deploy(MappingStructStoragePointerAlias);
  deployer.deploy(MappingStructStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(MappingStructStoragePointerAliasSubMapping);
  deployer.deploy(MappingStructStoragePointerAliasSubStruct);
  deployer.deploy(MappingStructStoragePointerNoAliasBase);
  deployer.deploy(MappingStructStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(MappingStructStoragePointerNoAliasSubMapping);
  deployer.deploy(MappingStructStoragePointerNoAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeLibraryStorageAliasBase);
  deployer.deploy(StructArrayFixedSizeLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeLibraryStorageAliasSubMapping);
  deployer.deploy(StructArrayFixedSizeLibraryStorageAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeLibraryStorageNoAliasBase);
  deployer.deploy(StructArrayFixedSizeLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeLibraryStorageNoAliasSubMapping);
  deployer.deploy(StructArrayFixedSizeLibraryStorageNoAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeStorageArgumentAliasBase);
  deployer.deploy(StructArrayFixedSizeStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeStorageArgumentAliasSubMapping);
  deployer.deploy(StructArrayFixedSizeStorageArgumentAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeStorageArgumentNoAliasBase);
  deployer.deploy(StructArrayFixedSizeStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeStorageArgumentNoAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeStoragePointerAlias);
  deployer.deploy(StructArrayFixedSizeStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeStoragePointerAliasSubMapping);
  deployer.deploy(StructArrayFixedSizeStoragePointerAliasSubStruct);
  deployer.deploy(StructArrayFixedSizeStoragePointerArrayPop);
  deployer.deploy(StructArrayFixedSizeStoragePointerNoAliasBase);
  deployer.deploy(StructArrayFixedSizeStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(StructArrayFixedSizeStoragePointerNoAliasSubMapping);
  deployer.deploy(StructArrayFixedSizeStoragePointerNoAliasSubStruct);
  deployer.deploy(StructLibraryStorageAliasBase);
  deployer.deploy(StructLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(StructLibraryStorageAliasSubMapping);
  deployer.deploy(StructLibraryStorageAliasSubStruct);
  deployer.deploy(StructLibraryStorageNoAliasBase);
  deployer.deploy(StructLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(StructLibraryStorageNoAliasSubMapping);
  deployer.deploy(StructLibraryStorageNoAliasSubStruct);
  deployer.deploy(StructMappingLibraryStorageAliasBase);
  deployer.deploy(StructMappingLibraryStorageAliasSubArrayFixedSize);
  deployer.deploy(StructMappingLibraryStorageAliasSubMapping);
  deployer.deploy(StructMappingLibraryStorageAliasSubStruct);
  deployer.deploy(StructMappingLibraryStorageNoAliasBase);
  deployer.deploy(StructMappingLibraryStorageNoAliasSubArrayFixedSize);
  deployer.deploy(StructMappingLibraryStorageNoAliasSubMapping);
  deployer.deploy(StructMappingLibraryStorageNoAliasSubStruct);
  deployer.deploy(StructMappingStorageArgumentAliasBase);
  deployer.deploy(StructMappingStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(StructMappingStorageArgumentAliasSubMapping);
  deployer.deploy(StructMappingStorageArgumentAliasSubStruct);
  deployer.deploy(StructMappingStorageArgumentNoAliasBase);
  deployer.deploy(StructMappingStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(StructMappingStorageArgumentNoAliasSubStruct);
  deployer.deploy(StructMappingStoragePointerAlias);
  deployer.deploy(StructMappingStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(StructMappingStoragePointerAliasSubMapping);
  deployer.deploy(StructMappingStoragePointerAliasSubStruct);
  deployer.deploy(StructMappingStoragePointerNoAliasBase);
  deployer.deploy(StructMappingStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(StructMappingStoragePointerNoAliasSubMapping);
  deployer.deploy(StructMappingStoragePointerNoAliasSubStruct);
  deployer.deploy(StructStorageArgumentAliasBase);
  deployer.deploy(StructStorageArgumentAliasSubArrayFixedSize);
  deployer.deploy(StructStorageArgumentAliasSubStruct);
  deployer.deploy(StructStorageArgumentNoAliasBase);
  deployer.deploy(StructStorageArgumentNoAliasSubArrayFixedSize);
  deployer.deploy(StructStorageArgumentNoAliasSubStruct);
  deployer.deploy(StructStoragePointerAlias);
  deployer.deploy(StructStoragePointerAliasSubArrayFixedSize);
  deployer.deploy(StructStoragePointerAliasSubMapping);
  deployer.deploy(StructStoragePointerAliasSubStruct);
  deployer.deploy(StructStoragePointerArrayPop);
  deployer.deploy(StructStoragePointerNoAliasBase);
  deployer.deploy(StructStoragePointerNoAliasSubArrayFixedSize);
  deployer.deploy(StructStoragePointerNoAliasSubMapping);
  deployer.deploy(StructStoragePointerNoAliasSubStruct);
};
